title: 软件丛林
email: suyu@intermaker.cn
description: >-
  复杂，源于简单。
  一叶一世界，一树一菩提。
  阳光普照，万物生长，充满希望。

locale: zh-CN
date_format: "%Y-%m-%d"

baseurl: ""
url: "https://suyuxp.github.io"
github_username:  suyuxp

markdown: kramdown
remote_theme: "suyuxp/so-simple-theme"
permalink: /:year/:month/:day/:title:output_ext

plugins:
  - jekyll-feed
  - jekyll-plantuml
  - jekyll-asciidoc

whitelist:
  - jekyll-asciidoc
  - jekyll-plantuml


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
